In [1]:
import pandas as pd
import numpy as np
from preprocessing import convert_utc_to_jfk

In [2]:
data = pd.read_csv('asos.txt')

In [3]:
data

,station,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,...,wxcodes,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,snowdepth
0,JFK,2019-11-01 00:24,66.00,66.00,100.00,180.00,26.00,0.00,29.68,M,...,BR,M,M,M,32.00,180.00,2019-11-01 00:10,66.00,KJFK 010024Z 18026G31KT 6SM BR OVC005 19/19 A2...,M
1,JFK,2019-11-01 00:51,67.00,67.00,100.00,180.00,22.00,0.00,29.66,1004.30,...,M,M,M,M,34.00,180.00,2019-11-01 00:46,66.90,KJFK 010051Z 18022G34KT 8SM OVC005 19/19 A2966...,M
2,JFK,2019-11-01 01:51,67.00,67.00,100.00,180.00,28.00,0.00,29.64,1003.50,...,M,M,M,M,40.00,180.00,2019-11-01 01:35,66.90,KJFK 010151Z 18028G37KT 8SM OVC006 19/19 A2964...,M
3,JFK,2019-11-01 02:51,67.00,67.00,100.00,180.00,31.00,0.00,29.60,1002.30,...,M,M,M,M,39.00,180.00,2019-11-01 02:47,66.90,KJFK 010251Z 18031G39KT 7SM OVC007 19/19 A2960...,M
4,JFK,2019-11-01 03:51,67.00,67.00,100.00,180.00,32.00,0.00,29.55,1000.50,...,M,M,M,M,42.00,170.00,2019-11-01 03:04,66.90,KJFK 010351Z 18032G39KT 8SM OVC008 19/19 A2955...,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11275,JFK,2020-12-30 19:51,40.00,24.10,52.88,200.00,11.00,0.00,30.30,1026.10,...,M,M,M,M,M,M,M,32.45,KJFK 301951Z 20011KT 10SM FEW045 FEW140 BKN250...,M
11276,JFK,2020-12-30 20:51,40.00,26.10,57.47,200.00,10.00,0.00,30.27,1025.10,...,M,M,M,M,M,M,M,32.87,KJFK 302051Z 20010KT 10SM FEW045 BKN250 04/M03...,M
11277,JFK,2020-12-30 21:51,39.00,25.00,56.86,200.00,13.00,0.00,30.25,1024.30,...,M,M,M,M,M,M,M,30.54,KJFK 302151Z 20013KT 10SM FEW045 BKN230 04/M04...,M
11278,JFK,2020-12-30 22:51,40.00,28.00,62.15,200.00,14.00,0.00,30.22,1023.40,...,M,M,M,M,M,M,M,31.35,KJFK 302251Z 20014KT 10SM BKN250 04/M02 A3022 ...,M
11279,JFK,2020-12-30 23:51,41.00,27.00,57.15,210.00,15.00,0.00,30.20,1022.60,...,M,M,M,M,M,M,M,32.45,KJFK 302351Z 21015KT 10SM BKN250 05/M03 A3020 ...,M

!!!!ВСЕ ПРОПУСКИ ПОМЕЧАЮТСЯ КАК M!!!!

- station:
идентификатор погодной станции (в нашем случае KJFK)
- valid:
timestamp точки измерения, его можно перевести через pd.to_datetime
- tmpf:
температура в фаренгейтах на уровне земли
- dwpf:
температура точки росы в фаренгейтах
- relh:
относительная влажность
- drct:
направление ветра с "настоящего" севера
- sknt:
скорость ветра в узлах
- p01i:
Часовое количество осадков за период от времени наблюдения до времени предыдущего часового сброса осадков. В зависимости от местности этот показатель несколько различается. Значения приведены в дюймах. Это значение может содержать или не содержать замерзшие осадки, растопленные каким-либо устройством на датчике или оцененные каким-либо другим способом. К сожалению, нам не известна авторитетная база данных, указывающая, на какой станции установлен тот или иной датчик.
- alti:
настройки альтиметра (дюймы рт. ст. давления)
- mslp:
давление на уровне моря в миллибарах
- vsby:
видимость в милях
- gust:
порывы ветра в узлах
- skyc1:
описание облачности (на уровне 1)
- skyc2:
описание облачности (на уровне 2)
- skyc3:
описание облачности (на уровне 3)
- skyc4:
описание облачности (на уровне 4)
- skyl1:
высота уровня 1 в футах
- skyl2:
высота уровня 2 в футах
- skyl3:
высота уровня 3 в футах
- skyl4:
высота уровня 4 в футах
- wxcodes:
коды погоды разделенные через пробел https://www.aviation.govt.nz/assets/licensing-and-certification/meteorology/aerodrome-weather-codes.pdf 
- feel:
температура по ощущениям
- ice_accretion_1hr:
нарастание льда за 1 час (дюймы)
- ice_accretion_3hr:
нарастание льда за 3 час (дюймы)
- ice_accretion_6hr:
нарастание льда за 6 час (дюймы)


- ремарки:

- peak_wind_gust:
пиковые порывы ветра в узлах
- peak_wind_drct:
направление пикового порыва ветра в градусах
- peak_wind_time:
время пикового времени порыва
- metar:
необработанный метар

In [4]:
data[data['skyc1'] == 'VV ']

,station,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,...,wxcodes,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,snowdepth
1138,JFK,2019-12-14 11:51,54.00,54.00,100.00,170.00,10.00,0.02,29.51,999.20,...,FG,M,M,M,M,M,M,54.00,KJFK 141151Z 17010KT 1/4SM R04R/2200V2400FT FG...,M
1146,JFK,2019-12-14 18:51,55.00,55.00,100.00,140.00,11.00,0.00,29.25,990.50,...,FG,M,M,M,M,M,M,55.00,KJFK 141851Z 14011KT 1/4SM R04R/1800V2200FT FG...,M
1149,JFK,2019-12-14 19:44,53.00,53.00,100.00,170.00,19.00,0.00,29.22,M,...,FG,M,M,M,M,M,M,53.10,KJFK 141944Z 17019KT 1/4SM R04R/1800V2800FT FG...,M
1150,JFK,2019-12-14 19:51,53.00,53.00,100.00,180.00,18.00,0.00,29.22,989.50,...,FG,M,M,M,M,M,M,53.10,KJFK 141951Z 18018KT 1/4SM R04R/2200V2800FT FG...,M
1151,JFK,2019-12-14 20:43,52.00,52.00,100.00,180.00,19.00,0.00,29.22,M,...,FG,M,M,M,28.00,180.00,2019-12-14 20:25,52.00,KJFK 142043Z AUTO 18019KT 1/4SM R04R/2000FT FG...,M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10925,JFK,2020-12-17 08:36,33.00,32.00,95.67,20.00,18.00,0.00,29.71,M,...,-SN BR,M,M,M,M,M,M,21.20,KJFK 170836Z 02018KT 1/2SM R04R/P6000FT -SN BR...,M
10926,JFK,2020-12-17 08:51,32.00,30.90,95.65,20.00,23.00,0.00,29.69,1005.30,...,-SN BR BLSN,M,M,M,M,M,M,18.31,KJFK 170851Z 02023G30KT 1/2SM R04R/5000V6000FT...,M
10927,JFK,2020-12-17 09:51,28.00,27.00,95.97,10.00,29.00,0.00,29.69,1005.40,...,-SN BLSN,M,M,M,M,M,M,11.42,KJFK 170951Z 01029G35KT 1/2SM R04R/4000V5500FT...,M
10928,JFK,2020-12-17 10:51,27.00,26.10,96.35,20.00,29.00,0.00,29.65,1004.10,...,-SN BLSN,M,M,M,M,M,M,10.05,KJFK 171051Z 02029G37KT 1/2SM R04R/4000VP6000F...,M
10929,JFK,2020-12-17 11:51,25.00,24.10,96.31,20.00,25.00,0.00,29.71,1006.00,...,-SN BLSN,M,M,M,M,M,M,8.34,KJFK 171151Z 02025G36KT 1SM R04R/5500VP6000FT ...,M

In [5]:
data[data['skyc1'] == 'M']

,station,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,...,wxcodes,ice_accretion_1hr,ice_accretion_3hr,ice_accretion_6hr,peak_wind_gust,peak_wind_drct,peak_wind_time,feel,metar,snowdepth
3148,JFK,2020-02-27 22:51,37.00,15.10,40.34,280.00,33.00,0.00,29.72,1006.40,...,M,M,M,M,M,M,M,23.03,KJFK 272251Z 28033G41KT 10SM 03/M09 A2972 RMK ...,M
4049,JFK,2020-04-01 07:23,39.00,33.00,79.17,M,M,0.00,29.86,M,...,M,M,M,M,M,M,M,M,KJFK 010723Z 04/01 A2986 RMK AO2 T00390006 CHI...,M
9352,JFK,2020-10-19 09:51,M,M,M,M,M,0.00,30.35,1027.90,...,M,M,M,M,M,M,M,M,KJFK 190951Z A3035 RMK AO2 SLP279 CHINO W $,M

In [6]:
data_enhanced = data[['station', 'valid', 'skyc1', 'skyc2', 'skyc3', 'skyc4', 'skyl1', 'skyl2', 'skyl3', 'skyl4']].copy()

In [7]:
data['skyc4'].unique()

array(['M', 'BKN', 'OVC', 'SCT', 'FEW'], dtype=object)

In [8]:
skyc_dict = {
    'CLR': 0,
    'FEW': 1,
    'SCT': 2,
    'BKN': 3,
    'OVC': 4,
    'VV ': 5,
    'M': 0,
    0:0
}

In [9]:
for col in ['skyc1', 'skyc2', 'skyc3', 'skyc4', 'skyl1', 'skyl2', 'skyl3', 'skyl4']:
    data_enhanced[col] = data_enhanced[col].astype(str).replace('M', 0)

for col in ['skyl1', 'skyl2', 'skyl3', 'skyl4']:
    data_enhanced[col] = data_enhanced[col].apply(lambda x: float(x) / 1000)

for col in ['skyc1', 'skyc2', 'skyc3', 'skyc4']:
    data_enhanced[col] = data_enhanced[col].apply(lambda x: skyc_dict[x])

for i, cols in enumerate(zip(['skyc1', 'skyc2', 'skyc3', 'skyc4'], ['skyl1', 'skyl2', 'skyl3', 'skyl4'])):
    col_1, col_2 = cols
    data_enhanced[f'inx_danjerous_{i + 1}'] = data_enhanced[col_1] / data_enhanced[col_2]
    data_enhanced[f'inx_danjerous_{i + 1}'] = data_enhanced[f'inx_danjerous_{i + 1}'].fillna(0)
    data_enhanced[f'inx_danjerous_{i + 1}'] = data_enhanced[f'inx_danjerous_{i + 1}'].apply(lambda x: 0 if x == np.inf else x)

In [10]:
data_enhanced

,station,valid,skyc1,skyc2,skyc3,skyc4,skyl1,skyl2,skyl3,skyl4,inx_danjerous_1,inx_danjerous_2,inx_danjerous_3,inx_danjerous_4
0,JFK,2019-11-01 00:24,4,0,0,0,0.5,0.0,0.0,0.0,8.000000,0.000000,0.00,0.0
1,JFK,2019-11-01 00:51,4,0,0,0,0.5,0.0,0.0,0.0,8.000000,0.000000,0.00,0.0
2,JFK,2019-11-01 01:51,4,0,0,0,0.6,0.0,0.0,0.0,6.666667,0.000000,0.00,0.0
3,JFK,2019-11-01 02:51,4,0,0,0,0.7,0.0,0.0,0.0,5.714286,0.000000,0.00,0.0
4,JFK,2019-11-01 03:51,4,0,0,0,0.8,0.0,0.0,0.0,5.000000,0.000000,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11275,JFK,2020-12-30 19:51,1,1,3,0,4.5,14.0,25.0,0.0,0.222222,0.071429,0.12,0.0
11276,JFK,2020-12-30 20:51,1,3,0,0,4.5,25.0,0.0,0.0,0.222222,0.120000,0.00,0.0
11277,JFK,2020-12-30 21:51,1,3,0,0,4.5,23.0,0.0,0.0,0.222222,0.130435,0.00,0.0
11278,JFK,2020-12-30 22:51,3,0,0,0,25.0,0.0,0.0,0.0,0.120000,0.000000,0.00,0.0
11279,JFK,2020-12-30 23:51,3,0,0,0,25.0,0.0,0.0,0.0,0.120000,0.000000,0.00,0.0

In [11]:
data_enhanced = convert_utc_to_jfk(data_enhanced)

In [12]:
data_enhanced

,station,valid,skyc1,skyc2,skyc3,skyc4,skyl1,skyl2,skyl3,skyl4,inx_danjerous_1,inx_danjerous_2,inx_danjerous_3,inx_danjerous_4,DATE_JFK,TIME_JFK
0,JFK,2019-11-01 00:24:00,4,0,0,0,0.5,0.0,0.0,0.0,8.000000,0.000000,0.00,0.0,2019-10-31,20:24:00
1,JFK,2019-11-01 00:51:00,4,0,0,0,0.5,0.0,0.0,0.0,8.000000,0.000000,0.00,0.0,2019-10-31,20:51:00
2,JFK,2019-11-01 01:51:00,4,0,0,0,0.6,0.0,0.0,0.0,6.666667,0.000000,0.00,0.0,2019-10-31,21:51:00
3,JFK,2019-11-01 02:51:00,4,0,0,0,0.7,0.0,0.0,0.0,5.714286,0.000000,0.00,0.0,2019-10-31,22:51:00
4,JFK,2019-11-01 03:51:00,4,0,0,0,0.8,0.0,0.0,0.0,5.000000,0.000000,0.00,0.0,2019-10-31,23:51:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11275,JFK,2020-12-30 19:51:00,1,1,3,0,4.5,14.0,25.0,0.0,0.222222,0.071429,0.12,0.0,2020-12-30,14:51:00
11276,JFK,2020-12-30 20:51:00,1,3,0,0,4.5,25.0,0.0,0.0,0.222222,0.120000,0.00,0.0,2020-12-30,15:51:00
11277,JFK,2020-12-30 21:51:00,1,3,0,0,4.5,23.0,0.0,0.0,0.222222,0.130435,0.00,0.0,2020-12-30,16:51:00
11278,JFK,2020-12-30 22:51:00,3,0,0,0,25.0,0.0,0.0,0.0,0.120000,0.000000,0.00,0.0,2020-12-30,17:51:00
11279,JFK,2020-12-30 23:51:00,3,0,0,0,25.0,0.0,0.0,0.0,0.120000,0.000000,0.00,0.0,2020-12-30,18:51:00

In [13]:
columns = ['valid', 'inx_danjerous_1', 'inx_danjerous_2', 'inx_danjerous_3', 'inx_danjerous_4', 'DATE_JFK', 'TIME_JFK']
data_to_merge = data_enhanced[columns].copy()

In [14]:
data['valid'] = pd.to_datetime(data['valid'])
data_to_merge['valid'] = pd.to_datetime(data_to_merge['valid'])

data_with_dangerous = pd.merge(data, data_to_merge, how='left', on='valid')

In [15]:
data_with_dangerous

,station,valid,tmpf,dwpf,relh,drct,sknt,p01i,alti,mslp,...,peak_wind_time,feel,metar,snowdepth,inx_danjerous_1,inx_danjerous_2,inx_danjerous_3,inx_danjerous_4,DATE_JFK,TIME_JFK
0,JFK,2019-11-01 00:24:00,66.00,66.00,100.00,180.00,26.00,0.00,29.68,M,...,2019-11-01 00:10,66.00,KJFK 010024Z 18026G31KT 6SM BR OVC005 19/19 A2...,M,8.000000,0.000000,0.00,0.0,2019-10-31,20:24:00
1,JFK,2019-11-01 00:51:00,67.00,67.00,100.00,180.00,22.00,0.00,29.66,1004.30,...,2019-11-01 00:46,66.90,KJFK 010051Z 18022G34KT 8SM OVC005 19/19 A2966...,M,8.000000,0.000000,0.00,0.0,2019-10-31,20:51:00
2,JFK,2019-11-01 01:51:00,67.00,67.00,100.00,180.00,28.00,0.00,29.64,1003.50,...,2019-11-01 01:35,66.90,KJFK 010151Z 18028G37KT 8SM OVC006 19/19 A2964...,M,6.666667,0.000000,0.00,0.0,2019-10-31,21:51:00
3,JFK,2019-11-01 02:51:00,67.00,67.00,100.00,180.00,31.00,0.00,29.60,1002.30,...,2019-11-01 02:47,66.90,KJFK 010251Z 18031G39KT 7SM OVC007 19/19 A2960...,M,5.714286,0.000000,0.00,0.0,2019-10-31,22:51:00
4,JFK,2019-11-01 03:51:00,67.00,67.00,100.00,180.00,32.00,0.00,29.55,1000.50,...,2019-11-01 03:04,66.90,KJFK 010351Z 18032G39KT 8SM OVC008 19/19 A2955...,M,5.000000,0.000000,0.00,0.0,2019-10-31,23:51:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11275,JFK,2020-12-30 19:51:00,40.00,24.10,52.88,200.00,11.00,0.00,30.30,1026.10,...,M,32.45,KJFK 301951Z 20011KT 10SM FEW045 FEW140 BKN250...,M,0.222222,0.071429,0.12,0.0,2020-12-30,14:51:00
11276,JFK,2020-12-30 20:51:00,40.00,26.10,57.47,200.00,10.00,0.00,30.27,1025.10,...,M,32.87,KJFK 302051Z 20010KT 10SM FEW045 BKN250 04/M03...,M,0.222222,0.120000,0.00,0.0,2020-12-30,15:51:00
11277,JFK,2020-12-30 21:51:00,39.00,25.00,56.86,200.00,13.00,0.00,30.25,1024.30,...,M,30.54,KJFK 302151Z 20013KT 10SM FEW045 BKN230 04/M04...,M,0.222222,0.130435,0.00,0.0,2020-12-30,16:51:00
11278,JFK,2020-12-30 22:51:00,40.00,28.00,62.15,200.00,14.00,0.00,30.22,1023.40,...,M,31.35,KJFK 302251Z 20014KT 10SM BKN250 04/M02 A3022 ...,M,0.120000,0.000000,0.00,0.0,2020-12-30,17:51:00
11279,JFK,2020-12-30 23:51:00,41.00,27.00,57.15,210.00,15.00,0.00,30.20,1022.60,...,M,32.45,KJFK 302351Z 21015KT 10SM BKN250 05/M03 A3020 ...,M,0.120000,0.000000,0.00,0.0,2020-12-30,18:51:00

In [16]:
data_with_dangerous.columns

Index(['station', 'valid', 'tmpf', 'dwpf', 'relh', 'drct', 'sknt', 'p01i',
       'alti', 'mslp', 'vsby', 'gust', 'skyc1', 'skyc2', 'skyc3', 'skyc4',
       'skyl1', 'skyl2', 'skyl3', 'skyl4', 'wxcodes', 'ice_accretion_1hr',
       'ice_accretion_3hr', 'ice_accretion_6hr', 'peak_wind_gust',
       'peak_wind_drct', 'peak_wind_time', 'feel', 'metar', 'snowdepth',
       'inx_danjerous_1', 'inx_danjerous_2', 'inx_danjerous_3',
       'inx_danjerous_4', 'DATE_JFK', 'TIME_JFK'],
      dtype='object')

In [17]:
data_with_dangerous.to_csv('data_enhanced_jfk_weather.csv', index=False)

In [19]:
len(data['wxcodes'].unique())

56

In [20]:
wxcodes_values = []
for val in list(data['wxcodes'].unique()):
    for one in val.split(' '):
        wxcodes_values.append(one)
wxcodes_values = list(set(wxcodes_values))

In [21]:
len(wxcodes_values)

35

In [22]:
wxcodes_values

['-DZ',
 '-PLSNRA',
 '-RA',
 '-FZRAPL',
 '-SNPL',
 '+SN',
 '-PLSN',
 'TS',
 '-FZRA',
 '-SNRA',
 'BLSN',
 'RA',
 'FG',
 '-RASNPL',
 'RAPL',
 '-SN',
 'TSRA',
 'BR',
 '-PLRA',
 '+RA',
 '+TSRA',
 '-RASN',
 'FZRAPL',
 'SN',
 '-PL',
 'VCFG',
 '-TSRA',
 'M',
 'HZ',
 'SQ',
 'FZFG',
 'PLRA',
 'VCTS',
 '-RAPL',
 'MIFG']

In [1]:
wx = ['-DZ',
 '-PLSNRA',
 '-RA',
 '-FZRAPL',
 '-SNPL',
 '+SN',
 '-PLSN',
 'TS',
 '-FZRA',
 '-SNRA',
 'BLSN',
 'RA',
 'FG',
 '-RASNPL',
 'RAPL',
 '-SN',
 'TSRA',
 'BR',
 '-PLRA',
 '+RA',
 '+TSRA',
 '-RASN',
 'FZRAPL',
 'SN',
 '-PL',
 'VCFG',
 '-TSRA',
 'M',
 'HZ',
 'SQ',
 'FZFG',
 'PLRA',
 'VCTS',
 '-RAPL',
 'MIFG']